[2025-10-13T08:36:37.491+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:36:37.517+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:36:37.526+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:36:37.527+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:36:37.544+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:36:37.553+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:36:37.556+0000] {standard_task_runner.py:72} INFO - Started process 154 to run task
[2025-10-13T08:36:37.557+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpmyg9tuii']
[2025-10-13T08:36:37.559+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask extract_load_group.load_customers
[2025-10-13T08:36:37.625+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:36:37.722+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:36:37.723+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:36:40.995+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:36:41.012+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T083637, end_date=20251013T083641
[2025-10-13T08:36:41.024+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:36:41.025+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task extract_load_group.load_customers (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 154)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:36:41.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:36:41.080+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:44:45.214+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:44:45.239+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:44:45.249+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:44:45.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:44:45.264+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:44:45.273+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=501) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:44:45.275+0000] {standard_task_runner.py:72} INFO - Started process 505 to run task
[2025-10-13T08:44:45.275+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp7itrkewf']
[2025-10-13T08:44:45.277+0000] {standard_task_runner.py:105} INFO - Job 81: Subtask extract_load_group.load_customers
[2025-10-13T08:44:45.352+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:44:45.457+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:44:45.458+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:45:05.656+0000] {load.py:30} INFO - Loaded 0 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-13T08:45:05.657+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:45:05.672+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:45:05.672+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T084445, end_date=20251013T084505
[2025-10-13T08:45:05.721+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:45:05.741+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:45:05.743+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:00.990+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:01.015+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:54:01.024+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:54:01.024+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:01.041+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:54:01.051+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=689) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:01.053+0000] {standard_task_runner.py:72} INFO - Started process 701 to run task
[2025-10-13T08:54:01.054+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmptk62rh8i']
[2025-10-13T08:54:01.055+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask extract_load_group.load_customers
[2025-10-13T08:54:01.114+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:01.210+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:54:01.211+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:54:21.022+0000] {load.py:30} INFO - Loaded 0 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-13T08:54:21.023+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:54:21.040+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:54:21.041+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T085401, end_date=20251013T085421
[2025-10-13T08:54:21.091+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:54:21.117+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:54:21.119+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:05:36.781+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:05:36.805+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:05:36.816+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:05:36.817+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:05:36.832+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:05:36.842+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1024) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:05:36.844+0000] {standard_task_runner.py:72} INFO - Started process 1033 to run task
[2025-10-13T09:05:36.844+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpdo29d84k']
[2025-10-13T09:05:36.845+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask extract_load_group.load_customers
[2025-10-13T09:05:36.913+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:05:37.004+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:05:37.005+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:05:41.931+0000] {load.py:30} INFO - Loaded 0 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-13T09:05:41.932+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:05:41.944+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:05:41.945+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T090536, end_date=20251013T090541
[2025-10-13T09:05:42.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:05:42.029+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:05:42.032+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:15:17.800+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:15:17.825+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:15:17.835+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:15:17.835+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:15:17.848+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:15:17.855+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:15:17.856+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpdfmaih_4']
[2025-10-13T09:15:17.857+0000] {standard_task_runner.py:72} INFO - Started process 1190 to run task
[2025-10-13T09:15:17.857+0000] {standard_task_runner.py:105} INFO - Job 159: Subtask extract_load_group.load_customers
[2025-10-13T09:15:17.918+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:15:18.012+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:15:18.013+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:15:22.745+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-13T09:15:22.746+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:15:22.760+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:15:22.761+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T091517, end_date=20251013T091522
[2025-10-13T09:15:22.807+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:15:22.832+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:15:22.833+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:34.207+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:34.234+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:20:34.247+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:20:34.248+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:34.266+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:20:34.275+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1287) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:34.278+0000] {standard_task_runner.py:72} INFO - Started process 1289 to run task
[2025-10-13T09:20:34.278+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpphhzds6j']
[2025-10-13T09:20:34.279+0000] {standard_task_runner.py:105} INFO - Job 170: Subtask extract_load_group.load_customers
[2025-10-13T09:20:34.375+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:34.495+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:20:34.496+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:20:45.495+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-13T09:20:45.496+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:20:45.509+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:20:45.510+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T092034, end_date=20251013T092045
[2025-10-13T09:20:45.544+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:20:45.575+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:20:45.578+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:15:41.934+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:15:41.956+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:41.966+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:41.967+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:15:41.985+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:15:41.993+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:15:41.995+0000] {standard_task_runner.py:72} INFO - Started process 136 to run task
[2025-10-14T04:15:41.995+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp4pnvdyjg']
[2025-10-14T04:15:41.996+0000] {standard_task_runner.py:105} INFO - Job 245: Subtask extract_load_group.load_customers
[2025-10-14T04:15:42.056+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:15:42.161+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:15:42.162+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:15:47.559+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:15:47.560+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:15:47.571+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:15:47.571+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T041541, end_date=20251014T041547
[2025-10-14T04:15:47.628+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:15:47.651+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:15:47.653+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:40.560+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:40.600+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:40.618+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:40.619+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:40.647+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:20:40.660+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=267) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:40.663+0000] {standard_task_runner.py:72} INFO - Started process 271 to run task
[2025-10-14T04:20:40.662+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmplrr0hddk']
[2025-10-14T04:20:40.665+0000] {standard_task_runner.py:105} INFO - Job 264: Subtask extract_load_group.load_customers
[2025-10-14T04:20:40.744+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:40.836+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:20:40.838+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:45.631+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:20:45.631+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:45.642+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:45.642+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042040, end_date=20251014T042045
[2025-10-14T04:20:45.695+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:45.722+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:45.723+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:15.447+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:15.469+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:15.479+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:15.479+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:15.494+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:22:15.503+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=503) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:15.505+0000] {standard_task_runner.py:72} INFO - Started process 511 to run task
[2025-10-14T04:22:15.505+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpg29xuz5t']
[2025-10-14T04:22:15.506+0000] {standard_task_runner.py:105} INFO - Job 326: Subtask extract_load_group.load_customers
[2025-10-14T04:22:15.570+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:15.669+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:22:15.670+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:19.965+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:22:19.966+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:19.979+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:19.980+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042215, end_date=20251014T042219
[2025-10-14T04:22:20.055+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:20.096+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:20.098+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:08.743+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:08.766+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:08.779+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:08.779+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:08.798+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:26:08.807+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=644) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:08.809+0000] {standard_task_runner.py:72} INFO - Started process 654 to run task
[2025-10-14T04:26:08.810+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpzf3798xr']
[2025-10-14T04:26:08.811+0000] {standard_task_runner.py:105} INFO - Job 351: Subtask extract_load_group.load_customers
[2025-10-14T04:26:08.877+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:08.991+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:26:08.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:15.091+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:26:15.092+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:15.105+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:15.105+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042608, end_date=20251014T042615
[2025-10-14T04:26:15.168+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:15.193+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:15.196+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:12.372+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:12.397+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:12.406+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:12.407+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:12.422+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:28:12.430+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=752) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:12.432+0000] {standard_task_runner.py:72} INFO - Started process 755 to run task
[2025-10-14T04:28:12.433+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '373', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpamvws_9u']
[2025-10-14T04:28:12.434+0000] {standard_task_runner.py:105} INFO - Job 373: Subtask extract_load_group.load_customers
[2025-10-14T04:28:12.502+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:12.610+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:28:12.611+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:16.930+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:28:16.930+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:16.941+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:16.942+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042812, end_date=20251014T042816
[2025-10-14T04:28:16.982+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:17.008+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:17.010+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:31:20.805+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:31:20.831+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:20.842+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:20.843+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:31:20.861+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:31:20.868+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1050) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:31:20.870+0000] {standard_task_runner.py:72} INFO - Started process 1055 to run task
[2025-10-14T04:31:20.870+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '444', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp2y1auf9d']
[2025-10-14T04:31:20.872+0000] {standard_task_runner.py:105} INFO - Job 444: Subtask extract_load_group.load_customers
[2025-10-14T04:31:20.942+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:31:21.082+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:31:21.084+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:31:25.974+0000] {load.py:30} INFO - Loaded 182 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:31:25.975+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:31:25.989+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:31:25.990+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T043120, end_date=20251014T043125
[2025-10-14T04:31:26.026+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:31:26.053+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:31:26.055+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
