[2025-10-14T04:21:01.620+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:21:01.645+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:21:01.658+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:21:01.659+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:21:01.676+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:21:01.685+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=339) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:21:01.687+0000] {standard_task_runner.py:72} INFO - Started process 340 to run task
[2025-10-14T04:21:01.687+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp57u182fq']
[2025-10-14T04:21:01.688+0000] {standard_task_runner.py:105} INFO - Job 281: Subtask transform
[2025-10-14T04:21:01.745+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:21:01.833+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:21:01.835+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:21:02.549+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id STRING,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:21:04.497+0000] {transform.py:170} ERROR - General error occurred: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/gcpl-469311/queries/1b17dd00-4234-49fb-bd2a-2c57db46fc07?maxResults=0&location=asia-southeast2&prettyPrint=false: Query error: Type not found: FLOAT at [6:15]

Location: asia-southeast2
Job ID: 1b17dd00-4234-49fb-bd2a-2c57db46fc07
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 144, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1650, in is_job_done
    self._reload_query_results(retry=retry, **reload_query_results_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1448, in _reload_query_results
    self._query_results = self._client._get_query_results(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2034, in _get_query_results
    resource = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 843, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/gcpl-469311/queries/1b17dd00-4234-49fb-bd2a-2c57db46fc07?maxResults=0&location=asia-southeast2&prettyPrint=false: Query error: Type not found: FLOAT at [6:15]

Location: asia-southeast2
Job ID: 1b17dd00-4234-49fb-bd2a-2c57db46fc07

[2025-10-14T04:21:04.505+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:21:04.516+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:21:04.517+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042101, end_date=20251014T042104
[2025-10-14T04:21:04.555+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:21:04.575+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:21:04.577+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:43.787+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:43.806+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:43.815+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:43.815+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:43.829+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:22:43.835+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=575) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:43.837+0000] {standard_task_runner.py:72} INFO - Started process 576 to run task
[2025-10-14T04:22:43.837+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp9476yv4h']
[2025-10-14T04:22:43.838+0000] {standard_task_runner.py:105} INFO - Job 341: Subtask transform
[2025-10-14T04:22:43.887+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:43.969+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:22:43.970+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:44.680+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id STRING,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:22:48.053+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:22:48.053+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:22:50.303+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:22:50.304+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:22:50.708+0000] {transform.py:170} ERROR - General error occurred: 400 No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]; reason: invalidQuery, location: query, message: No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]

Location: asia-southeast2
Job ID: 9d1236f9-64d2-4d82-aafc-3abe69d0e6e9
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 162, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.BadRequest: 400 No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]; reason: invalidQuery, location: query, message: No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]

Location: asia-southeast2
Job ID: 9d1236f9-64d2-4d82-aafc-3abe69d0e6e9

[2025-10-14T04:22:50.713+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:50.726+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:50.727+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042243, end_date=20251014T042250
[2025-10-14T04:22:50.766+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:50.785+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:50.787+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:39.828+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:39.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:39.859+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:39.860+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:39.873+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:26:39.880+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=717) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:39.881+0000] {standard_task_runner.py:72} INFO - Started process 718 to run task
[2025-10-14T04:26:39.882+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp02dz7lgz']
[2025-10-14T04:26:39.883+0000] {standard_task_runner.py:105} INFO - Job 365: Subtask transform
[2025-10-14T04:26:39.931+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:40.011+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:26:40.013+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:40.752+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id INT64,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:26:43.796+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:26:43.797+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:26:45.689+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:26:45.690+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:26:47.348+0000] {transform.py:167} INFO - dim_customers query executed successfully.
[2025-10-14T04:26:47.348+0000] {transform.py:159} INFO - Executing dim_products query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_products AS target
    USING (
        SELECT
            p.product_id ,
            p.product_name ,
            p.category ,
            p.price
        FROM gcpl-469311.datalabs_techtest.stg_products p
    ) AS source
    ON target.product_id = source.product_id

    WHEN MATCHED THEN
    UPDATE SET
        target.product_name = source.product_name,
        target.category = source.category,
        target.price = source.price

    WHEN NOT MATCHED THEN
    INSERT (product_id, product_name, category, price)
    VALUES (source.product_id, source.product_name, source.category, source.price)
    ;
    
[2025-10-14T04:26:48.921+0000] {transform.py:167} INFO - dim_products query executed successfully.
[2025-10-14T04:26:48.922+0000] {transform.py:159} INFO - Executing dim_dates query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_date AS target
    USING (
        SELECT
            t.transaction_id ,
            t.transaction_date
        FROM gcpl-469311.datalabs_techtest.stg_transactions t
    ) AS source
    ON target.transaction_id = source.transaction_id

    WHEN MATCHED THEN
    UPDATE SET
        target.transaction_date = source.transaction_date

    WHEN NOT MATCHED THEN
    INSERT (transaction_id, transaction_date)
    VALUES (source.transaction_id, source.transaction_date);
    
[2025-10-14T04:26:49.126+0000] {transform.py:170} ERROR - General error occurred: 404 Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2; reason: notFound, message: Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2

Location: asia-southeast2
Job ID: a9925c71-e8dd-4a25-8c93-1de8cf5acab0
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 162, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.NotFound: 404 Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2; reason: notFound, message: Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2

Location: asia-southeast2
Job ID: a9925c71-e8dd-4a25-8c93-1de8cf5acab0

[2025-10-14T04:26:49.131+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:49.146+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:49.146+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042639, end_date=20251014T042649
[2025-10-14T04:26:49.213+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:49.231+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:49.233+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:45.991+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:46.012+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:46.022+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:46.022+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:46.036+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:28:46.043+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=824) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:46.045+0000] {standard_task_runner.py:72} INFO - Started process 825 to run task
[2025-10-14T04:28:46.045+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '389', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpuo_cr88r']
[2025-10-14T04:28:46.046+0000] {standard_task_runner.py:105} INFO - Job 389: Subtask transform
[2025-10-14T04:28:46.105+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:46.196+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:28:46.198+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:47.127+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id INT64,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:28:50.210+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:28:50.211+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:28:51.886+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:28:51.886+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:28:53.617+0000] {transform.py:167} INFO - dim_customers query executed successfully.
[2025-10-14T04:28:53.617+0000] {transform.py:159} INFO - Executing dim_products query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_products AS target
    USING (
        SELECT
            p.product_id ,
            p.product_name ,
            p.category ,
            p.price
        FROM gcpl-469311.datalabs_techtest.stg_products p
    ) AS source
    ON target.product_id = source.product_id

    WHEN MATCHED THEN
    UPDATE SET
        target.product_name = source.product_name,
        target.category = source.category,
        target.price = source.price

    WHEN NOT MATCHED THEN
    INSERT (product_id, product_name, category, price)
    VALUES (source.product_id, source.product_name, source.category, source.price)
    ;
    
[2025-10-14T04:28:55.332+0000] {transform.py:167} INFO - dim_products query executed successfully.
[2025-10-14T04:28:55.333+0000] {transform.py:159} INFO - Executing dim_dates query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_dates AS target
    USING (
        SELECT
            t.transaction_id ,
            t.transaction_date
        FROM gcpl-469311.datalabs_techtest.stg_transactions t
    ) AS source
    ON target.transaction_id = source.transaction_id

    WHEN MATCHED THEN
    UPDATE SET
        target.transaction_date = source.transaction_date

    WHEN NOT MATCHED THEN
    INSERT (transaction_id, transaction_date)
    VALUES (source.transaction_id, source.transaction_date);
    
[2025-10-14T04:28:57.120+0000] {transform.py:167} INFO - dim_dates query executed successfully.
[2025-10-14T04:28:57.121+0000] {transform.py:159} INFO - Executing dim_campaigns query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_campaigns AS target
    USING (
        SELECT
            mc.campaign_id ,
            mc.campaign_name ,
            mc.start_date ,
            mc.end_date ,
            mc.channel
        FROM gcpl-469311.datalabs_techtest.stg_marketing_campaigns mc
    ) AS source

    ON target.campaign_id = source.campaign_id

    WHEN MATCHED THEN
    UPDATE SET
        target.campaign_name = source.campaign_name ,
        target.start_date = source.start_date ,
        target.end_date = source.end_date ,
        target.channel = source.channel

    WHEN NOT MATCHED THEN
    INSERT (campaign_id, campaign_name, start_date, end_date, channel)
    VALUES (source.campaign_id, source.campaign_name, source.start_date, source.end_date, source.channel);
    
[2025-10-14T04:28:58.807+0000] {transform.py:167} INFO - dim_campaigns query executed successfully.
[2025-10-14T04:28:58.808+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:58.821+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:58.822+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042846, end_date=20251014T042858
[2025-10-14T04:28:58.867+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:58.887+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:58.889+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:41.705+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:41.726+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:41.735+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:41.735+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:41.748+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:35:41.755+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1173) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:41.757+0000] {standard_task_runner.py:72} INFO - Started process 1174 to run task
[2025-10-14T04:35:41.757+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '461', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp5yshtpgn']
[2025-10-14T04:35:41.758+0000] {standard_task_runner.py:105} INFO - Job 461: Subtask transform
[2025-10-14T04:35:41.806+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:41.889+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:35:41.890+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:35:42.585+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id INT64,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:35:46.139+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:35:46.140+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:35:47.776+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:35:47.776+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:35:49.432+0000] {transform.py:167} INFO - dim_customers query executed successfully.
[2025-10-14T04:35:49.433+0000] {transform.py:159} INFO - Executing dim_products query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_products AS target
    USING (
        SELECT
            p.product_id ,
            p.product_name ,
            p.category ,
            p.price
        FROM gcpl-469311.datalabs_techtest.stg_products p
    ) AS source
    ON target.product_id = source.product_id

    WHEN MATCHED THEN
    UPDATE SET
        target.product_name = source.product_name,
        target.category = source.category,
        target.price = source.price

    WHEN NOT MATCHED THEN
    INSERT (product_id, product_name, category, price)
    VALUES (source.product_id, source.product_name, source.category, source.price)
    ;
    
[2025-10-14T04:35:51.104+0000] {transform.py:167} INFO - dim_products query executed successfully.
[2025-10-14T04:35:51.105+0000] {transform.py:159} INFO - Executing dim_dates query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_dates AS target
    USING (
        SELECT
            t.transaction_id ,
            t.transaction_date
        FROM gcpl-469311.datalabs_techtest.stg_transactions t
    ) AS source
    ON target.transaction_id = source.transaction_id

    WHEN MATCHED THEN
    UPDATE SET
        target.transaction_date = source.transaction_date

    WHEN NOT MATCHED THEN
    INSERT (transaction_id, transaction_date)
    VALUES (source.transaction_id, source.transaction_date);
    
[2025-10-14T04:35:53.035+0000] {transform.py:167} INFO - dim_dates query executed successfully.
[2025-10-14T04:35:53.035+0000] {transform.py:159} INFO - Executing dim_campaigns query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_campaigns AS target
    USING (
        SELECT
            mc.campaign_id ,
            mc.campaign_name ,
            mc.start_date ,
            mc.end_date ,
            mc.channel
        FROM gcpl-469311.datalabs_techtest.stg_marketing_campaigns mc
    ) AS source

    ON target.campaign_id = source.campaign_id

    WHEN MATCHED THEN
    UPDATE SET
        target.campaign_name = source.campaign_name ,
        target.start_date = source.start_date ,
        target.end_date = source.end_date ,
        target.channel = source.channel

    WHEN NOT MATCHED THEN
    INSERT (campaign_id, campaign_name, start_date, end_date, channel)
    VALUES (source.campaign_id, source.campaign_name, source.start_date, source.end_date, source.channel);
    
[2025-10-14T04:35:54.691+0000] {transform.py:167} INFO - dim_campaigns query executed successfully.
[2025-10-14T04:35:54.692+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:35:54.703+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:35:54.704+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T043541, end_date=20251014T043554
[2025-10-14T04:35:54.744+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:35:54.760+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:35:54.762+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
