[2025-10-13T08:37:07.808+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:07.837+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.851+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.851+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:07.881+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:37:07.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:07.895+0000] {standard_task_runner.py:72} INFO - Started process 239 to run task
[2025-10-13T08:37:07.895+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpd48bz_cm']
[2025-10-13T08:37:07.897+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask extract_load_group.load_marketing_campaigns
[2025-10-13T08:37:07.969+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:08.097+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:37:08.098+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:10.918+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:10.935+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T083707, end_date=20251013T083710
[2025-10-13T08:37:10.968+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:10.968+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task extract_load_group.load_marketing_campaigns (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 239)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:11.001+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:11.013+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:52.007+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:52.033+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.046+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.047+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:52.064+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:54:52.072+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=776) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:72} INFO - Started process 781 to run task
[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpvx16cqyy']
[2025-10-13T08:54:52.076+0000] {standard_task_runner.py:105} INFO - Job 122: Subtask extract_load_group.load_marketing_campaigns
[2025-10-13T08:54:52.148+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:52.269+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:54:52.271+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:05.450+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-13T08:55:05.451+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:05.466+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:05.467+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T085452, end_date=20251013T085505
[2025-10-13T08:55:05.518+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:05.540+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:05.542+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:51.762+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:51.784+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.793+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.794+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:51.813+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-13T09:20:51.822+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1329) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:51.824+0000] {standard_task_runner.py:72} INFO - Started process 1341 to run task
[2025-10-13T09:20:51.824+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpkfycurlg']
[2025-10-13T09:20:51.826+0000] {standard_task_runner.py:105} INFO - Job 184: Subtask extract_load_group.load_marketing_campaigns
[2025-10-13T09:20:51.894+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:51.997+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T09:20:51.998+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:01.728+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-13T09:21:01.729+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:01.740+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:01.741+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T092051, end_date=20251013T092101
[2025-10-13T09:21:01.800+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:01.823+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:21:01.826+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:21:01.829+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-10-14T04:16:04.354+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:16:04.379+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.390+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.391+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:16:04.407+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:16:04.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:16:04.416+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2025-10-14T04:16:04.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmple3db737']
[2025-10-14T04:16:04.418+0000] {standard_task_runner.py:105} INFO - Job 253: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:16:04.480+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:16:04.591+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:16:04.592+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:16:09.529+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:16:09.530+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:16:09.543+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:16:09.544+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T041604, end_date=20251014T041609
[2025-10-14T04:16:09.575+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:16:09.597+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:16:09.599+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:54.522+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:54.544+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.554+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.554+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:54.570+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:20:54.578+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=316) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:54.580+0000] {standard_task_runner.py:72} INFO - Started process 320 to run task
[2025-10-14T04:20:54.581+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpvw1r715e']
[2025-10-14T04:20:54.582+0000] {standard_task_runner.py:105} INFO - Job 277: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:20:54.661+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:54.780+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:20:54.781+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:59.003+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:20:59.004+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:59.015+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:59.015+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042054, end_date=20251014T042059
[2025-10-14T04:20:59.091+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:59.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:35.773+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:35.796+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.804+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.805+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:35.819+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:22:35.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=552) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:35.827+0000] {standard_task_runner.py:72} INFO - Started process 559 to run task
[2025-10-14T04:22:35.828+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpjkzpgls1']
[2025-10-14T04:22:35.829+0000] {standard_task_runner.py:105} INFO - Job 335: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:22:35.886+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:35.984+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:22:35.985+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:40.155+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:22:40.156+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:40.170+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:40.170+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042235, end_date=20251014T042240
[2025-10-14T04:22:40.220+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:40.244+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:40.246+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:32.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:32.594+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.606+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.607+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:32.624+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:26:32.631+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=690) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:32.633+0000] {standard_task_runner.py:72} INFO - Started process 693 to run task
[2025-10-14T04:26:32.633+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '360', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp_gsdbkn6']
[2025-10-14T04:26:32.636+0000] {standard_task_runner.py:105} INFO - Job 360: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:26:32.700+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:32.803+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:26:32.804+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:37.039+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:26:37.040+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:37.051+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:37.052+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042632, end_date=20251014T042637
[2025-10-14T04:26:37.105+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:37.133+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:37.136+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:38.241+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:38.272+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.286+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:38.310+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:28:38.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=804) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:38.321+0000] {standard_task_runner.py:72} INFO - Started process 807 to run task
[2025-10-14T04:28:38.321+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpn48syj4d']
[2025-10-14T04:28:38.322+0000] {standard_task_runner.py:105} INFO - Job 384: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:28:38.397+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:38.519+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:28:38.521+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:43.232+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:28:43.232+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:43.247+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:43.248+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042838, end_date=20251014T042843
[2025-10-14T04:28:43.315+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:43.325+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-10-14T04:28:43.342+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:43.346+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:32.785+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:32.808+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.819+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.820+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:32.839+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:35:32.846+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:72} INFO - Started process 1158 to run task
[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '456', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp_0t6bbgt']
[2025-10-14T04:35:32.850+0000] {standard_task_runner.py:105} INFO - Job 456: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:35:32.930+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:33.048+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:35:33.049+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:35:36.970+0000] {load.py:30} INFO - Loaded 65 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:35:36.970+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:35:36.982+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:35:36.983+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T043532, end_date=20251014T043536
[2025-10-14T04:35:37.041+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:35:37.071+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:35:37.073+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
