[2025-10-13T08:37:07.782+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:07.811+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.821+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.822+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:07.841+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:37:07.850+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:07.852+0000] {standard_task_runner.py:72} INFO - Started process 232 to run task
[2025-10-13T08:37:07.856+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpu_wdkofg']
[2025-10-13T08:37:07.858+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask extract_load_group.load_transactions
[2025-10-13T08:37:07.939+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:08.055+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:37:08.057+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:10.912+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:10.932+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T083707, end_date=20251013T083710
[2025-10-13T08:37:10.987+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:10.988+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task extract_load_group.load_transactions (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 232)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:11.039+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:11.066+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:37:11.068+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:52.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:52.030+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.042+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.043+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:52.063+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:54:52.071+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=774) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:72} INFO - Started process 780 to run task
[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpz0hq7uqg']
[2025-10-13T08:54:52.075+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask extract_load_group.load_transactions
[2025-10-13T08:54:52.146+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:52.268+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:54:52.270+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:06.076+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T08:55:06.078+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:06.095+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:06.096+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T085452, end_date=20251013T085506
[2025-10-13T08:55:06.160+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:06.182+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:06.185+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:51.762+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:51.784+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.793+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.794+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:51.813+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-13T09:20:51.822+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1330) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:51.825+0000] {standard_task_runner.py:72} INFO - Started process 1340 to run task
[2025-10-13T09:20:51.824+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpskr8rmvt']
[2025-10-13T09:20:51.826+0000] {standard_task_runner.py:105} INFO - Job 183: Subtask extract_load_group.load_transactions
[2025-10-13T09:20:51.894+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:51.998+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T09:20:52.000+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:04.354+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T09:21:04.354+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:04.367+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:04.368+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T092051, end_date=20251013T092104
[2025-10-13T09:21:04.401+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:04.426+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:21:04.428+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:16:04.367+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:16:04.391+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.401+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.403+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:16:04.419+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:16:04.428+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:16:04.430+0000] {standard_task_runner.py:72} INFO - Started process 185 to run task
[2025-10-14T04:16:04.430+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpozjzzjok']
[2025-10-14T04:16:04.431+0000] {standard_task_runner.py:105} INFO - Job 257: Subtask extract_load_group.load_transactions
[2025-10-14T04:16:04.490+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:16:04.603+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:16:04.604+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:16:09.730+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:16:09.730+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:16:09.741+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:16:09.742+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T041604, end_date=20251014T041609
[2025-10-14T04:16:09.785+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:16:09.805+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:16:09.807+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:54.520+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:54.543+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.554+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.554+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:54.571+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:20:54.578+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:54.580+0000] {standard_task_runner.py:72} INFO - Started process 321 to run task
[2025-10-14T04:20:54.582+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpcfs5my7z']
[2025-10-14T04:20:54.584+0000] {standard_task_runner.py:105} INFO - Job 276: Subtask extract_load_group.load_transactions
[2025-10-14T04:20:54.661+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:54.780+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:20:54.781+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:59.003+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:20:59.004+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:59.015+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:59.015+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042054, end_date=20251014T042059
[2025-10-14T04:20:59.091+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:59.119+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:59.121+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:35.772+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:35.795+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.803+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.804+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:35.817+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:22:35.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=551) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:35.827+0000] {standard_task_runner.py:72} INFO - Started process 558 to run task
[2025-10-14T04:22:35.831+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpczjs75ry']
[2025-10-14T04:22:35.833+0000] {standard_task_runner.py:105} INFO - Job 337: Subtask extract_load_group.load_transactions
[2025-10-14T04:22:35.887+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:35.979+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:22:35.980+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:41.007+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:22:41.007+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:41.019+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:41.019+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042235, end_date=20251014T042241
[2025-10-14T04:22:41.068+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:41.089+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:41.091+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:32.586+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:32.611+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.623+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:32.644+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:26:32.653+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=688) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:32.655+0000] {standard_task_runner.py:72} INFO - Started process 699 to run task
[2025-10-14T04:26:32.656+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '363', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp43dihfzp']
[2025-10-14T04:26:32.658+0000] {standard_task_runner.py:105} INFO - Job 363: Subtask extract_load_group.load_transactions
[2025-10-14T04:26:32.721+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:32.823+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:26:32.824+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:36.805+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:26:36.806+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:36.821+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:36.822+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042632, end_date=20251014T042636
[2025-10-14T04:26:36.887+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:36.916+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:36.918+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:38.241+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:38.272+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.286+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:38.309+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:28:38.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=801) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:38.320+0000] {standard_task_runner.py:72} INFO - Started process 806 to run task
[2025-10-14T04:28:38.321+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp6652kkfk']
[2025-10-14T04:28:38.322+0000] {standard_task_runner.py:105} INFO - Job 383: Subtask extract_load_group.load_transactions
[2025-10-14T04:28:38.397+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:38.521+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:28:38.522+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:42.996+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:28:42.996+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:43.008+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:43.009+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042838, end_date=20251014T042843
[2025-10-14T04:28:43.074+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:43.103+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:43.106+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:32.785+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:32.808+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.819+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.819+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:32.836+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:35:32.845+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1152) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:72} INFO - Started process 1154 to run task
[2025-10-14T04:35:32.848+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '455', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp9ewtvafq']
[2025-10-14T04:35:32.850+0000] {standard_task_runner.py:105} INFO - Job 455: Subtask extract_load_group.load_transactions
[2025-10-14T04:35:32.933+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:33.049+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:35:33.050+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:35:38.285+0000] {load.py:30} INFO - Loaded 34 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:35:38.286+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:35:38.301+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:35:38.302+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T043532, end_date=20251014T043538
[2025-10-14T04:35:38.375+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:35:38.401+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:35:38.403+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
