[2025-10-13T08:37:07.789+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:07.818+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.829+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.829+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:07.846+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:37:07.857+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:07.859+0000] {standard_task_runner.py:72} INFO - Started process 235 to run task
[2025-10-13T08:37:07.860+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp122yh631']
[2025-10-13T08:37:07.861+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask extract_load_group.load_products
[2025-10-13T08:37:07.946+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:08.069+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:37:08.070+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:10.918+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:10.935+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T083707, end_date=20251013T083710
[2025-10-13T08:37:10.978+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:10.979+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task extract_load_group.load_products (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 235)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:11.047+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:11.061+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:52.001+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:52.029+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.042+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.043+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:52.062+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:54:52.071+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=775) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:72} INFO - Started process 778 to run task
[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpdigze9jr']
[2025-10-13T08:54:52.076+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask extract_load_group.load_products
[2025-10-13T08:54:52.146+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:52.267+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:54:52.269+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:02.884+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-13T08:55:02.886+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:02.903+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:02.904+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T085452, end_date=20251013T085502
[2025-10-13T08:55:02.943+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:02.967+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:02.969+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:51.750+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:51.772+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.782+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.783+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:51.796+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-13T09:20:51.804+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1333) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:51.806+0000] {standard_task_runner.py:72} INFO - Started process 1335 to run task
[2025-10-13T09:20:51.807+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmplo84m19t']
[2025-10-13T09:20:51.808+0000] {standard_task_runner.py:105} INFO - Job 180: Subtask extract_load_group.load_products
[2025-10-13T09:20:51.879+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:51.980+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T09:20:51.981+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:04.598+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-13T09:21:04.598+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:04.613+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:04.613+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T092051, end_date=20251013T092104
[2025-10-13T09:21:04.664+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:04.693+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:21:04.695+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:16:04.356+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:16:04.381+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.391+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.392+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:16:04.408+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:16:04.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=176) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:16:04.417+0000] {standard_task_runner.py:72} INFO - Started process 180 to run task
[2025-10-14T04:16:04.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpnc10tth4']
[2025-10-14T04:16:04.419+0000] {standard_task_runner.py:105} INFO - Job 255: Subtask extract_load_group.load_products
[2025-10-14T04:16:04.481+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:16:04.596+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:16:04.597+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:16:10.184+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:16:10.185+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:16:10.199+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:16:10.200+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T041604, end_date=20251014T041610
[2025-10-14T04:16:10.257+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:16:10.286+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:16:10.289+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:54.536+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:54.557+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.567+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.568+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:54.589+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:20:54.599+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:54.601+0000] {standard_task_runner.py:72} INFO - Started process 326 to run task
[2025-10-14T04:20:54.601+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp55_7h4b8']
[2025-10-14T04:20:54.603+0000] {standard_task_runner.py:105} INFO - Job 278: Subtask extract_load_group.load_products
[2025-10-14T04:20:54.684+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:54.800+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:20:54.802+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:59.494+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:20:59.495+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:59.506+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:59.507+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042054, end_date=20251014T042059
[2025-10-14T04:20:59.556+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:59.590+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:59.592+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:59.606+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-10-14T04:22:35.772+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:35.794+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.804+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.804+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:35.818+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:22:35.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=555) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:35.827+0000] {standard_task_runner.py:72} INFO - Started process 557 to run task
[2025-10-14T04:22:35.827+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp0r3jcne6']
[2025-10-14T04:22:35.828+0000] {standard_task_runner.py:105} INFO - Job 336: Subtask extract_load_group.load_products
[2025-10-14T04:22:35.886+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:35.984+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:22:35.985+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:40.947+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:22:40.948+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:40.962+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:40.963+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042235, end_date=20251014T042240
[2025-10-14T04:22:41.028+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:41.051+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:41.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:32.569+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:32.594+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.605+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:32.621+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:26:32.629+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=689) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:32.631+0000] {standard_task_runner.py:72} INFO - Started process 691 to run task
[2025-10-14T04:26:32.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '359', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpur8pj4pk']
[2025-10-14T04:26:32.633+0000] {standard_task_runner.py:105} INFO - Job 359: Subtask extract_load_group.load_products
[2025-10-14T04:26:32.698+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:32.801+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:26:32.802+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:37.772+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:26:37.773+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:37.785+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:37.785+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042632, end_date=20251014T042637
[2025-10-14T04:26:37.833+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:37.859+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:37.861+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:38.241+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:38.274+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.289+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.290+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:38.315+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:28:38.327+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=803) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:38.329+0000] {standard_task_runner.py:72} INFO - Started process 811 to run task
[2025-10-14T04:28:38.330+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpn0qhrg3i']
[2025-10-14T04:28:38.331+0000] {standard_task_runner.py:105} INFO - Job 385: Subtask extract_load_group.load_products
[2025-10-14T04:28:38.405+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:38.529+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:28:38.530+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:43.423+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:28:43.424+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:43.436+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:43.436+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042838, end_date=20251014T042843
[2025-10-14T04:28:43.487+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:43.523+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:43.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:32.786+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:32.808+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.818+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.819+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:32.837+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:35:32.846+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:72} INFO - Started process 1156 to run task
[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '459', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpxg4zrm2r']
[2025-10-14T04:35:32.850+0000] {standard_task_runner.py:105} INFO - Job 459: Subtask extract_load_group.load_products
[2025-10-14T04:35:32.934+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:33.051+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:35:33.053+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:35:37.503+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:35:37.505+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:35:37.519+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:35:37.519+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T043532, end_date=20251014T043537
[2025-10-14T04:35:37.563+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:35:37.592+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:35:37.595+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
