[2025-10-13T08:37:07.798+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:07.827+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.839+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:07.860+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:37:07.871+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:07.874+0000] {standard_task_runner.py:72} INFO - Started process 237 to run task
[2025-10-13T08:37:07.874+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpc_fm96uw']
[2025-10-13T08:37:07.876+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask extract_load_group.load_transaction_items
[2025-10-13T08:37:07.954+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:08.073+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:37:08.074+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:10.912+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:10.932+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T083707, end_date=20251013T083710
[2025-10-13T08:37:10.957+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:10.958+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task extract_load_group.load_transaction_items (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 237)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:11.025+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:11.048+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:37:11.051+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:52.015+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:52.042+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.054+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.055+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:52.076+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:54:52.085+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=777) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:52.087+0000] {standard_task_runner.py:72} INFO - Started process 786 to run task
[2025-10-13T08:54:52.088+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpzpgda1lc']
[2025-10-13T08:54:52.089+0000] {standard_task_runner.py:105} INFO - Job 123: Subtask extract_load_group.load_transaction_items
[2025-10-13T08:54:52.162+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:52.289+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:54:52.290+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:03.519+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-13T08:55:03.521+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:03.538+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:03.538+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T085452, end_date=20251013T085503
[2025-10-13T08:55:03.591+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:03.614+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:03.615+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:51.752+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:51.773+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.784+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.785+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:51.801+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-13T09:20:51.809+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1331) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:51.811+0000] {standard_task_runner.py:72} INFO - Started process 1338 to run task
[2025-10-13T09:20:51.812+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmplzav4cci']
[2025-10-13T09:20:51.813+0000] {standard_task_runner.py:105} INFO - Job 181: Subtask extract_load_group.load_transaction_items
[2025-10-13T09:20:51.882+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:51.983+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T09:20:51.985+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:02.360+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-13T09:21:02.360+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:02.372+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:02.373+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T092051, end_date=20251013T092102
[2025-10-13T09:21:02.415+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:02.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:16:04.362+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:16:04.388+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.399+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.400+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:16:04.415+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:16:04.424+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=177) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:16:04.426+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2025-10-14T04:16:04.426+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpx2mrclba']
[2025-10-14T04:16:04.428+0000] {standard_task_runner.py:105} INFO - Job 256: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:16:04.490+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:16:04.604+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:16:04.605+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:16:09.242+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:16:09.242+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:16:09.256+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:16:09.257+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T041604, end_date=20251014T041609
[2025-10-14T04:16:09.302+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:16:09.327+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:16:09.329+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:54.538+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:54.562+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.575+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.576+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:54.596+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:20:54.608+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=315) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:54.611+0000] {standard_task_runner.py:72} INFO - Started process 328 to run task
[2025-10-14T04:20:54.611+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp8twhtaur']
[2025-10-14T04:20:54.612+0000] {standard_task_runner.py:105} INFO - Job 279: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:20:54.691+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:54.805+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:20:54.807+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:59.326+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:20:59.326+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:59.338+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:59.339+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042054, end_date=20251014T042059
[2025-10-14T04:20:59.403+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:59.431+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:59.433+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:35.773+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:35.795+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.803+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.804+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:35.818+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:22:35.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=553) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:35.827+0000] {standard_task_runner.py:72} INFO - Started process 556 to run task
[2025-10-14T04:22:35.832+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpr2no0nxo']
[2025-10-14T04:22:35.833+0000] {standard_task_runner.py:105} INFO - Job 338: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:22:35.890+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:35.983+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:22:35.984+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:40.490+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:22:40.491+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:40.505+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:40.505+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042235, end_date=20251014T042240
[2025-10-14T04:22:40.541+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:40.566+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:40.568+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:32.569+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:32.594+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.605+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:32.622+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:26:32.629+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=687) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:32.632+0000] {standard_task_runner.py:72} INFO - Started process 692 to run task
[2025-10-14T04:26:32.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmppldtt84n']
[2025-10-14T04:26:32.633+0000] {standard_task_runner.py:105} INFO - Job 361: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:26:32.698+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:32.802+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:26:32.803+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:37.244+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:26:37.245+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:37.256+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:37.257+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042632, end_date=20251014T042637
[2025-10-14T04:26:37.305+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:37.331+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:37.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:38.241+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:38.271+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.286+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:38.307+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:28:38.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=800) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:38.320+0000] {standard_task_runner.py:72} INFO - Started process 805 to run task
[2025-10-14T04:28:38.320+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpesyopse_']
[2025-10-14T04:28:38.322+0000] {standard_task_runner.py:105} INFO - Job 386: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:28:38.397+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:38.523+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:28:38.524+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:43.120+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:28:43.120+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:43.132+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:43.133+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042838, end_date=20251014T042843
[2025-10-14T04:28:43.195+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:43.224+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:43.228+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:32.786+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:32.809+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.818+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.819+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:32.837+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:35:32.845+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1150) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:32.847+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpmhvr0ppe']
[2025-10-14T04:35:32.848+0000] {standard_task_runner.py:72} INFO - Started process 1155 to run task
[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:105} INFO - Job 457: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:35:32.935+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:33.050+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:35:33.051+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:35:36.914+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:35:36.915+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:35:36.931+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:35:36.931+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T043532, end_date=20251014T043536
[2025-10-14T04:35:37.000+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:35:37.031+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:35:37.033+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
